Sprint 1
Iker-elorrieta/RetoADPSP3 pull request #1
Opened 2020-12-21 17:42 UTC by Egoitz-Gomez

Sprint 1

2020-12-23 12:24 UTC, Iker-elorrieta requested changes
Teneís que cambiar la inserción de datos en las estaciones. Además teneis que relacionar los espacios naturales con los municipios y crear una prueba.

Lo demás correcto. Animo

2020-12-23 12:24 UTC, Iker-elorrieta commented on src/Insert/Consultas.java
> +
Los datos no estan correctos, no funciona la inserción. Os he enviado un email con las especificaciones para su correción

2020-12-23 12:24 UTC, Iker-elorrieta commented on src/Insert/Consultas.java
> +
No relacionáis municipios con espacios naturales. Hay que crear un elemento de prueba en esa tabla.

2021-01-11 18:18 UTC, Egoitz-Gomez reviewed
sprint 1 corregido

2021-01-12 11:29 UTC, Iker-elorrieta commented
Ok, seguimos.

2021-01-12 11:29 UTC, merged