Sptint2
Iker-elorrieta/RetoADPSP3 pull request #2
Opened 2021-01-14 17:32 UTC by Egoitz-Gomez

sprint 2

2021-01-15 11:02 UTC, Iker-elorrieta commented on Json/leerJson/leerJson.java
> +					if (valor.getAsString().contains("datos_horarios")) {
quizas no se deberian leer los 3.

2021-01-15 11:05 UTC, Iker-elorrieta requested changes
1-. No están incluidas las pruebas. Para probar el cliente he tenido que modificar la IP. Hay que dejar el proyecto para que se pueda probar el local.
2-. En cuanto a la ejecución. Hay que hacer los XML desde los objetos de Java. No desde los JSON.
3-. Veo que hay una parada de 1 segundo. Creo que deberíamos quitarla si fuese posible. Con ello el proceso tardaría menos.
4-. Aparecen caracteres extraños en la base de datos. Se deberían visualizar correctamente.
5-. Una vez terminado el proceso de carga, se queda con el mensaje SEGS. Doy por hecho que se queda así para volverse actualizar la hora que siguiente.
6-. El cliente crea el usuario correctamente el base de datos, pero luego da error la mostrar el municipio. No se ve que error da ni en que linea.
7-. He puesto unos comentarios sobre LeerJson.

2021-01-15 11:05 UTC, Iker-elorrieta commented on Json/leerJson/leerJson.java
> +			// REVISALO IBAI GILIPOLLAS
Estos comentarios no deberían existir

2021-01-15 11:05 UTC, Iker-elorrieta commented on Json/leerJson/leerJson.java
> +				case "documentName":
Todos los String deberían ser final y con variables

2021-01-15 11:05 UTC, Iker-elorrieta commented on Json/leerJson/leerJson.java
> +				System.out.println("Objeto");
Los logs hay que pulirlos. No pueden existir comentarios no informativos en el log

2021-01-19 15:46 UTC, jonanderlopez5 commented
comentario

2021-01-19 15:47 UTC, Egoitz-Gomez reviewed
sprint 2 corregido

2021-01-19 22:12 UTC, Iker-elorrieta requested changes
Sigue apareciendo una IP de un equipo concreto. Debería aparecer localhost.
En el código se ven codificaciones extrañas.  (Contrase�a)
El cliente no funciona. No deja logearse.
Las pruebas superar el 85%. La carga se hace correctamente. Se podrían eliminar municipios que no tengan datos ( no tengas estaciones meteorológicas).

2021-01-21 19:04 UTC, Iker-elorrieta approved these changes
Parece estar todo correcto,

No veo como se inicia el servidor para que se descargue los json. La idea sería iniciar el servidor y que se baje los json y luego que cree el serverSocket para recibir las peticiones de los clientes.

2021-01-21 19:04 UTC, merged